### ISSUE TITLE
Server side https requests from gawati-portal to the template server fail

### ISSUE THREAD

**Issue by kohsah** [gawati/gawati-portal#6]
The template server can be deployed over https with local certificates. 
In such cases the https request by the portal for the template fails with an exception [1]

https requests to other public urls work (.e.g. https://google.com, https://yahoo.com) 

[1]  Exception:

javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
    at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1937)
    at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
    at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
    at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1478)
    at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
    at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
    at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1050)
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1363)
    at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:735)
    at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
    at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:138)
    at SSLPoke.main(SSLPoke.java:21)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
    at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
    at sun.security.validator.Validator.validate(Validator.java:260)
    at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
    at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
    at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
    at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1460)
    ... 9 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:145)
    at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)
    at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
    at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
    ... 15 more

**Comment by kohsah** [comment]
Test case:

Run this XQuery on eXist:

```
xquery version "3.0";

import module namespace http = "http://expath.org/ns/http-client";
(: url with local cert, otherwise use https://localhost with a locally installed cert :)
let $url := 'https://alldev.gawati.org'
let $request := <http:request href="{$url}" method="head"/>
let $response := http:send-request($request)
return
    <xml>{$response}</xml>
```

It will fail with the: PKIX path building failed: sun.security.provider.certpath. exception.

**Step 1:**
During installation, grab the certificate for alldev.gawati.org: 

`echo -n | openssl s_client -connect alldev.gawati.org:443  | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p'  > ALLDEV.crt`

**Step 2:**

Import this key into a new local trust store called `LocalTrustStore` with password `password` and alias `ALL_ROOT_CA`:

`keytool -import -trustcacerts -storepass password  -file "/path/to/ALLDEV.crt" -alias ALL_ROOT_CA -keystore /path/to/LocalTrustStore`

`keytool` is found in the jdk bin folder

**Step 3:**

Set this as the trustStore for the eXist instance, by passing it as a startup up option (this is the last line `bin/startup.bat` for yajsw set appropriately): 

`%JAVA_RUN% "%JAVA_OPTS%"  -Dexist.home="%EXIST_HOME%" -Djavax.net.ssl.trustStore="/path/to/LocalTrustStore" -Djavax.net.ssl.trustStorePassword=password -jar "%EXIST_HOME%\start.jar" jetty %JAVA_ARGS%`

Restart exist.

**Step 4:**

Execute the test case again, you will get a successful response. 

**Caveat:**

Since eXist doesn't have access to java's own trustStore, you cannot make https requests to other external sites (e.g. https://google.com will fail) . If we access any such external services from within eXist via server side calls, we just need to the certificates for these sites to our LocalTrustStore.

**Comment by kohsah** [comment]
Useful for testing: SSLPoke to simulate the same problem, run it without the` System.setProperty() `for the failure test case, and with the `system.setProperty()` (with the local trust store created and populated as described in the earlier comment)

```java
package org.test;

import javax.net.ssl.SSLSocket;
import javax.net.ssl.SSLSocketFactory;
import java.io.*;

/** Establish a SSL connection to a host and port, writes a byte and
 * prints the response. See
 * http://confluence.atlassian.com/display/JIRA/Connecting+to+SSL+services
 */
public class SSLPoke {
    public static void main(String[] args) {
        
        // -Djavax.net.ssl.trustStore="D:\develop\github\testSSL\LocalTrustStore"
        System.setProperty("javax.net.ssl.trustStore", "D:\\develop\\github\\testSSL\\LocalTrustStore");
        System.setProperty("javax.net.ssl.trustStorePassword", "password");
                
        String sHost = "alldev.gawati.org";
        String sPort = "443";
        try {
            SSLSocketFactory sslsocketfactory = (SSLSocketFactory) SSLSocketFactory.getDefault();
            SSLSocket sslsocket = (SSLSocket) sslsocketfactory.createSocket(sHost, Integer.parseInt(sPort));

            InputStream in = sslsocket.getInputStream();
            OutputStream out = sslsocket.getOutputStream();

            // Write a test byte to get a reaction :)
            out.write(1);

            while (in.available() > 0) {
                System.out.print(in.read());
            }
            System.out.println("Successfully connected");

        } catch (Exception exception) {
            exception.printStackTrace();
        }
    }
}
```

**Comment by ccsmart** [comment]
This should be considered where no CA certificate is available.
